theme: jekyll-theme-minimal
title: Acacia
description: Experimenting with wood
logo: /assets/img/Acacia.png
exclude:
  - docker-compose.yml
favicon: /assets/img/favicon.ico
social:
  instagram: https://instagram.com/acacia.joinery
