theme: jekyll-theme-minimal
title: Acacia
description: Cabinetry, Fitted Furniture & general Home Improvement
logo: /assets/img/Acacia.png
exclude:
  - docker-compose.yml
favicon: /assets/img/favicon.ico
social:
  instagram: https://instagram.com/acacia.joinery

plugins: [jekyll-paginate]

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
paginate: 5
