theme: jekyll-theme-minimal
title: Acacia
description: Cabinetry, Fitted & free standing Furniture, general woodwork & Home Improvement
location: North & West Yorkshire
logo: /assets/img/Acacia.png
exclude:
  - docker-compose.yml
social:
  instagram: https://instagram.com/acacia.woodwork
  email: contact@acacia.ws

plugins: [jekyll-paginate]

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
paginate: 3
